// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID      uint   `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"` // 主键
	Comment string `json:"user_name"`                                                              // 账户名
}
