// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMoney = "Money"

// Money mapped from table <Money>
type Money struct {
	ID        uint   `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"` // primary key
	UID       uint   `json:"uid"`                                                                    // user id
	ItemID    string `json:"money_id"`                                                               // item id
	Amount    string `json:"amount"`                                                                 // amount
	Icon      string `json:"icon"`                                                                   // icon url(or build-in icon id)
	MoneyType string `json:"money_type"`                                                             // money type
}
