// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameData = "data"

// Data mapped from table <data>
type Data struct {
	ID       uint   `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"` // key id
	UserName string `json:"user_name"`                                                              // username
	Password string `json:"password"`                                                               // password
}
