// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "User"

// User mapped from table <User>
type User struct {
	ID       uint   `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"` // key id
	UserName string `json:"user_name"`                                                              // username
	Password string `json:"password"`                                                               // password
}
